-- Per-turn conversation debug log -- TEMPORARY, current-build-phase
-- diagnostic tool (2026-09-06, per Rick's explicit request after a live
-- demo hit several bugs that couldn't be diagnosed after the fact
-- because nothing records what was actually said turn-to-turn:
-- conversation_state only ever holds the LATEST snapshot, and api.py
-- logs no request/reply text anywhere). Not architected for the long
-- haul on purpose -- drop this table (and its call site in
-- v2_voice_query) once the app is stable and this stops earning its
-- keep.
--
-- Deliberately more private than the `events` table above: `events`
-- exists specifically to anonymize load data and contribute it to a
-- shared aggregate pool (waiver Section 4). This table holds raw
-- spoken text, which is NOT covered by that section's disclosure --
-- it must never be anonymized-and-shared the way `events` is, only
-- ever readable by the user who generated it, same isolation
-- guarantee as every other per-user table (RLS via auth.uid(), not
-- application-code filtering).

create table public.conversation_debug_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  input_text text not null,
  tool_name text not null,
  reply_text text not null,
  created_at timestamptz not null default now()
);

alter table public.conversation_debug_log enable row level security;

create policy "conversation_debug_log_all_own" on public.conversation_debug_log
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on public.conversation_debug_log to authenticated;

-- Postgres identity columns need an explicit sequence-usage grant
-- separate from the table grant above, or every insert from the
-- `authenticated` role fails with "permission denied for sequence".
grant usage, select on sequence public.conversation_debug_log_id_seq to authenticated;
