-- Video log (2026-09-29, Rick's own idea): a small, per-user TEXT record
-- tying a real range video -- which stays on the shooter's own phone,
-- Ballistica never sees or stores it -- to exactly what rifle, load, and
-- conditions were in play that day, so reviewing footage later means
-- reviewing the RIGHT data, picked from what was actually saved rather
-- than retyped from memory. Same reasoning as conversation_debug_log
-- above: this is text, not media, so storing it costs essentially nothing
-- and needs none of the storage-bucket/cost decisions video itself would.
--
-- rifle_name/load_name are a snapshot (plain text), not a foreign key to
-- rifles/loads -- a rifle or load can be renamed or deleted later, and the
-- log entry should still say what was actually used that day, not silently
-- follow a rename or break on a delete.
--
-- Run this in the Supabase SQL Editor, same as every prior migration --
-- DDL isn't something the REST API can apply itself.

create table public.video_logs (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null,
  rifle_name text not null,
  load_name text,
  session_date date not null,
  temp_f double precision,
  humidity_pct double precision,
  wind_mph double precision,
  wind_clock double precision,
  altitude_ft double precision,
  pressure_inhg double precision,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.video_logs enable row level security;

create policy "video_logs_all_own" on public.video_logs
  for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

grant select, insert, update, delete on public.video_logs to authenticated;

-- Postgres identity columns need an explicit sequence-usage grant
-- separate from the table grant above, or every insert from the
-- `authenticated` role fails with "permission denied for sequence".
grant usage, select on sequence public.video_logs_id_seq to authenticated;
