// Verifies ballistica/web/engine.js (the offline-mode JS port of the
// Python ballistics engine) against real reference output from the
// Python engine itself (scripts/engine_parity_cases.json, generated by
// scripts/generate_engine_parity_cases.py).
//
// Run: node scripts/check_engine_parity.js
// Regenerate reference cases first if the Python engine changed:
//   python -m scripts.generate_engine_parity_cases

const fs = require("fs");
const path = require("path");
const BallisticaEngine = require("../ballistica/web/engine.js");

const casesPath = path.join(__dirname, "engine_parity_cases.json");
const cases = JSON.parse(fs.readFileSync(casesPath, "utf8"));

// Tight but not absurd -- these are floating point RK4 integrations,
// not symbolic math, so exact bit-for-bit equality isn't the bar.
// 1e-6 absolute/relative is far tighter than anything a shooter could
// perceive (a MOA/MRAD/click discrepancy at this scale is meaningless
// in practice) while still catching a genuine porting bug.
const ABS_TOL = 1e-6;
const REL_TOL = 1e-6;

function closeEnough(a, b) {
  if (a === b) return true;
  const diff = Math.abs(a - b);
  return diff <= ABS_TOL || diff <= REL_TOL * Math.max(Math.abs(a), Math.abs(b));
}

let failures = 0;
let totalFields = 0;

for (const testCase of cases) {
  const { label, input, expected } = testCase;
  let actual;
  try {
    actual = BallisticaEngine.solveDropAtRange(input);
  } catch (e) {
    console.error(`[FAIL] ${label}: threw ${e.message}`);
    failures++;
    continue;
  }

  const mismatches = [];
  for (const key of Object.keys(expected)) {
    totalFields++;
    if (!closeEnough(actual[key], expected[key])) {
      mismatches.push(`${key}: expected ${expected[key]}, got ${actual[key]}`);
    }
  }

  if (mismatches.length > 0) {
    console.error(`[FAIL] ${label}:\n  ` + mismatches.join("\n  "));
    failures++;
  } else {
    console.log(`[OK]   ${label}`);
  }
}

console.log(`\n${cases.length - failures}/${cases.length} cases passed (${totalFields} fields checked)`);
if (failures > 0) {
  console.error(`${failures} case(s) FAILED -- the JS engine has drifted from the Python engine.`);
  process.exit(1);
}
